In [13]:
import numpy as np
a=[[1, 2, 3],[2, 4, 9],[1, 0, 0]]
b=[[1, 2, 3],[2, 4, 9],[1, 0, 0]]
c=[[0,0,0],[0,0,0],[0,0,0]]
for i in range(3):
    for j in range(3):
        for k in range(3):
            c[i][j]+=a[i][k]*b[k][j]
print(c)

[[8, 10, 21], [19, 20, 42], [1, 2, 3]]


In [19]:
import numpy as np

In [25]:
M=np.array([[1, 2, 3],[2, 4, 5],[1, 0, 0]])
for i in range(3):
    for j in range(3):
        print(M[i][j],end=" ")
    print()
print(M.T)

1 2 3 
2 4 5 
1 0 0 
[[1 2 1]
 [2 4 0]
 [3 5 0]]


In [31]:
M=np.array([[1, 2, 3],[2, 4, 5],[1, 0, 0]])
Trans=np.array([[0,0,0],[0,0,0],[0,0,0]])
for i in range(3):
    for j in range(3):
        Trans[i][j]=M[j][i]
print(Trans)

[[1 2 1]
 [2 4 0]
 [3 5 0]]


In [3]:
a=1+1j
print(a.conjugate())

(1-1j)


In [4]:
import numpy as np
import cmath as cm
M=np.array([[complex(1,1), 2, complex(3,-1)],[2, complex(4,-2), 5],[complex(1,1), 0, 0]])
conj=M
for i in range(3):
    for k in range(3):
        conj[i][k]=M[i][k].conjugate()
print(conj)

[[1.-1.j 2.-0.j 3.+1.j]
 [2.-0.j 4.+2.j 5.-0.j]
 [1.-1.j 0.-0.j 0.-0.j]]


In [29]:
#Pauli's Matrices
import numpy as np
import cmath as cm
sigma_x=np.array([[0,1],[1,0]])
sigma_y=np.array([[0,-1j],[1j,0]])
sigma_z=np.array([[1,0],[0,-1]])
sigma_x_theta=sigma_x.copy()
sigma_y_theta=sigma_y.copy()
sigma_z_theta=sigma_z.copy()
I=np.array([[1,0],[0,1]])
for i in range(2):
    for j in range(2):
        sigma_x_theta[i][j]=sigma_x[j][i].conjugate()
        sigma_y_theta[i][j]=sigma_y[j][i].conjugate()
        sigma_z_theta[i][j]=sigma_z[j][i].conjugate()
print("sigma_x= ",sigma_x, "\n","sigma_x_theta= ",sigma_x_theta,"\n","sigma_y= ",sigma_y, "\n","sigma_y_theta= ",sigma_y_theta,"\n","sigma_z= ",sigma_z, "\n","sigma_z_theta= ",sigma_z_theta)
def mat_multi(c,d):
    cd=np.array([[0,0],[0,0]])
    for i in range(2):
        for j in range(2):
            for k in range(2):
                cd+=c[i][k]*d[k][j]
def hermitian(a,b):
    for i in range(2):
        for j in range(2):
            if a[i][j]==b[i][j]:
                return True
if hermitian(sigma_x,sigma_x_theta):
    print("Hermitian Matrix")
if hermitian(sigma_y,sigma_y_theta):
    print("Hermitian Matrix")
if hermitian(sigma_z,sigma_z_theta):
    print("Hermitian Matrix")

sigma_x=  [[0 1]
 [1 0]] 
 sigma_x_theta=  [[0 1]
 [1 0]] 
 sigma_y=  [[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]] 
 sigma_y_theta=  [[ 0.-0.j  0.-1.j]
 [-0.+1.j  0.-0.j]] 
 sigma_z=  [[ 1  0]
 [ 0 -1]] 
 sigma_z_theta=  [[ 1  0]
 [ 0 -1]]
Hermitian Matrix
Hermitian Matrix
Hermitian Matrix
